cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'git'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'roundup'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'wakeonlan'
brew 'maven'
brew 'ant'

cask '1password'
cask 'adium'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'iterm2'
cask 'mapbox-studio'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'tcl'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'xquartz'
